apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot3-apr30-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot3-apr30-1:3c1a897066f9818253adb086ced6e1ef9955f1ae@sha256:f3882987c97e2061fef175712cf61e18ef315ea8978533a576639aa7195f8238 # use pre-built to bootstrap
          name: app-inference
